/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SIGNUP_H_RPCGEN
#define _SIGNUP_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct SignUpargs {
	char *username;
	char *password;
};
typedef struct SignUpargs SignUpargs;

#define SIGNUP_PROG 0x2345111
#define SIGNUP_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define signup 1
extern  int * signup_1(SignUpargs *, CLIENT *);
extern  int * signup_1_svc(SignUpargs *, struct svc_req *);
extern int signup_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define signup 1
extern  int * signup_1();
extern  int * signup_1_svc();
extern int signup_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_SignUpargs (XDR *, SignUpargs*);

#else /* K&R C */
extern bool_t xdr_SignUpargs ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SIGNUP_H_RPCGEN */
