/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "SignUp.h"

bool_t
xdr_SignUpargs (XDR *xdrs, SignUpargs *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->username, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->password, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
